### ISSUE TITLE
Black stripes in polar areas

### ISSUE THREAD

**Issue by ohnonot** [jmozmoz/cloudmap#13]
Hello,
thank you for providing this!

I have used the script from my own machine a few times, and then [from here](https://github.com/apollo-ng/cloudmap). _Every time_ there's been some irregularities esp. in the Arctic, see e.g. [here](https://raw.githubusercontent.com/apollo-ng/cloudmap/master/global.jpg) - I'm talking about the sharp-edged black areas in the upper left, and also smaller in the upper middle, slightly to the right.

Is it possible to improve this somehow?

I understand there's some limitations to how the original images can be combined into the final image, esp. around the poles. It would be great if python offered some intelligent filling of these obvious gaps (I'm just guessing here)?

**Comment by jmozmoz** [comment]
The images at the polar regions are just faked. Geo stationary sattelites don't see the polar regions. The "clouds" there are created by mirroring the values of the upper/lower lattitues to not have a black hole. 

It is done here: https://github.com/jmozmoz/cloudmap/blob/master/cloudmap/geo_dundee.py#L266

If you change the 95 to something higher, a larger area is covered by "fake" clouds. This could remove the black areas, but might also remove some of the real cloud images.

**Comment by ohnonot** [comment]
thanks!
