### ISSUE TITLE
Tracking bug for 0.6.0 release

### ISSUE THREAD

**Issue by jmozmoz** [jmozmoz/cloudmap#6]
New features in 0.6.0:
- Multiprocessing (of course 5 processes is best, because there 5 satellite images to re-project)
- Support for second projecting library: cartopy (until now only pyresample is supported) 
- Python 3 support: At the moment cartopy supports Python 3, pyresample will add Python 3 support with the release 1.1.1 (https://github.com/mraspaud/pyresample/commit/fde4205a3dbe13fd85655ebb67d88adb88ed67c3)
- Reorganization of code structure

**Comment by chron0** [comment]
Thank you.
