### ISSUE TITLE
"Cannot download (all) satellite images!"

### ISSUE THREAD

**Issue by MacDaddy1660B** [jmozmoz/cloudmap#8]
Hi there,

Been having some problems with create_map lately. I'm not sure when the issue arose, but it started at least a few weeks ago. Opening a terminal and running `create_map -d` gives

`create_map -d

Search backward for images from: 2017-09-05 15:15:32.190895
cannot download image: http://www.sat.dundee.ac.uk/xrit/057.0E/MET/2017/9/5/1500/2017_9_5_1500_MET7_2_S2_grid.jpeg
cannot download image: http://www.sat.dundee.ac.uk/xrit/057.0E/MET/2017/9/5/1200/2017_9_5_1200_MET7_2_S2_grid.jpeg
cannot download image: http://www.sat.dundee.ac.uk/xrit/057.0E/MET/2017/9/5/1200/2017_9_5_1200_MET7_2_S2_grid.jpeg
...`

I notice the satellite at 57E was replaced with one at 41.5E, but it seems the script it still looking for the one at 57E. I have updated to version 0.9.2.

`create_map -V
0.9.2`

Thanks for any help.

**Comment by MacDaddy1660B** [comment]
Oops. I didn't upgrade my json file. Sorry about this. Issue resolved.

**Comment by jmozmoz** [comment]
I released the latest version as wheel, but then the setup.py is not called during installation, which would update the json file automatically. In the future, I will source packages again when pushing to pypi.
